version: "2"
services:
  node:
    build: 
      context: ./docker/node
      args: 
        APP: $APP
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"